### ISSUE TITLE
Stop File not found！

### ISSUE THREAD

**Issue by bucky1119** [JiscaH/Fortran#1]
compilation is ok “gfortran -O3 ../sqa_fileIO.f90 ../sqa_general.f90 Sequoia_SA.f90 -o sequoia
”
This is my command：“./sequoia  --geno ./File/MyData.txt --lifehist ./File/G15_with_SireAndDam_LifeHist.txt --ageprior ./File/AgePriors.txt --out ./File/G15_with_SireAndDam_outcome --ped --maybePO --maybeRel --pairs --verbose --log
”
Does not run and displays" STOP File --verbose --log not found!"

**Comment by JiscaH** [comment]
Hi Bucky,

Thanks for your message! I will add a more informative error message when it expects a file name or parameter or so, but gets something that starts with '--'.

Please do let me know if you run into any other issues - the Fortran stand-alone version isn't as extensively tested or user friendly as the R package.

Best, Jisca
